/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Etapa;

import Controlador.CtrlEtapa;
import Controlador.CtrlPostulante;
import Modelo.FormatoPruebaDaoJDBC;
import Modelo.Postulacion;
import Modelo.PostulacionDaoJDBC;
import Modelo.Postulante;
import Modelo.PostulanteDaoJDBC;
import Modelo.Prueba;
import Modelo.PruebaDaoJDBC;
import Modelo.Puesto;
import Modelo.PuestoDaoJDBC;
import java.sql.Date;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MC1
 */
public class NuevaPrueba extends javax.swing.JPanel {
    private Postulacion pstl;
    private ArrayList<Postulacion> listaPostulacionPrueba;
    private ArrayList<String> listaPuestosPr;

    /**
     * Creates new form NuevaPruebas
     */
    public NuevaPrueba() {
        initComponents();
        activarFormSeleccionarPuesto(false);
        activarFormRegistrarPrueba(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelObservaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabelIdPostulante = new javax.swing.JLabel();
        jLabelPuesto = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jButtonCancelar = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jLabelFormatoHora = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jComboBoxHH = new javax.swing.JComboBox<>();
        jLabelFecha = new javax.swing.JLabel();
        jComboBoxMM = new javax.swing.JComboBox<>();
        jLabelHora = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jLabelObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelObservaciones.setText("Observaciones");
        jLabelObservaciones.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabelObservaciones.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabelObservaciones.setPreferredSize(new java.awt.Dimension(100, 16));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(4);
        jTextAreaObservaciones.setMaximumSize(new java.awt.Dimension(552, 68));
        jTextAreaObservaciones.setMinimumSize(new java.awt.Dimension(552, 68));
        jTextAreaObservaciones.setPreferredSize(new java.awt.Dimension(552, 68));
        jScrollPane2.setViewportView(jTextAreaObservaciones);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Malo");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setMaximumSize(new java.awt.Dimension(80, 40));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(80, 40));
        jRadioButton1.setPreferredSize(new java.awt.Dimension(80, 40));
        jRadioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Regular");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setMaximumSize(new java.awt.Dimension(80, 40));
        jRadioButton2.setMinimumSize(new java.awt.Dimension(80, 40));
        jRadioButton2.setPreferredSize(new java.awt.Dimension(80, 40));
        jRadioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Bueno");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setMaximumSize(new java.awt.Dimension(80, 40));
        jRadioButton3.setMinimumSize(new java.awt.Dimension(80, 40));
        jRadioButton3.setPreferredSize(new java.awt.Dimension(80, 40));
        jRadioButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Muy bueno");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setMaximumSize(new java.awt.Dimension(80, 40));
        jRadioButton4.setMinimumSize(new java.awt.Dimension(80, 40));
        jRadioButton4.setPreferredSize(new java.awt.Dimension(80, 40));
        jRadioButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Excelente");
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setMaximumSize(new java.awt.Dimension(80, 40));
        jRadioButton5.setMinimumSize(new java.awt.Dimension(80, 40));
        jRadioButton5.setPreferredSize(new java.awt.Dimension(80, 40));
        jRadioButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextFieldDNI.setMaximumSize(new java.awt.Dimension(125, 22));
        jTextFieldDNI.setMinimumSize(new java.awt.Dimension(125, 22));
        jTextFieldDNI.setPreferredSize(new java.awt.Dimension(125, 22));

        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDni.setText("Ingrese DNI:");
        jLabelDni.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabelDni.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabelDni.setPreferredSize(new java.awt.Dimension(100, 16));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Prueba");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 29));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(125, 22));
        jButtonBuscar.setMinimumSize(new java.awt.Dimension(125, 22));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(125, 22));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabelIdPostulante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdPostulante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdPostulante.setText("Postulante:");
        jLabelIdPostulante.setEnabled(false);
        jLabelIdPostulante.setMaximumSize(new java.awt.Dimension(552, 17));
        jLabelIdPostulante.setMinimumSize(new java.awt.Dimension(552, 17));
        jLabelIdPostulante.setPreferredSize(new java.awt.Dimension(552, 17));

        jLabelPuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPuesto.setText("Seleccione puesto:");
        jLabelPuesto.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabelPuesto.setMinimumSize(new java.awt.Dimension(100, 120));
        jLabelPuesto.setPreferredSize(new java.awt.Dimension(120, 16));

        jComboBox1.setMaximumSize(new java.awt.Dimension(250, 22));
        jComboBox1.setMinimumSize(new java.awt.Dimension(250, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(250, 22));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDescripcion.setText("Descripción de la prueba");
        jLabelDescripcion.setMaximumSize(new java.awt.Dimension(552, 16));
        jLabelDescripcion.setMinimumSize(new java.awt.Dimension(552, 16));
        jLabelDescripcion.setPreferredSize(new java.awt.Dimension(552, 16));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(4);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jTextAreaDescripcion.setMaximumSize(new java.awt.Dimension(552, 68));
        jTextAreaDescripcion.setMinimumSize(new java.awt.Dimension(552, 68));
        jTextAreaDescripcion.setPreferredSize(new java.awt.Dimension(552, 68));
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelResultado.setText("Resultado");
        jLabelResultado.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabelResultado.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabelResultado.setPreferredSize(new java.awt.Dimension(100, 16));

        jLabelFormatoHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFormatoHora.setText(":");
        jLabelFormatoHora.setEnabled(false);
        jLabelFormatoHora.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelFormatoHora.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabelFormatoHora.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabelFormatoHora.setPreferredSize(new java.awt.Dimension(60, 16));

        jDateChooserFecha.setDateFormatString("d MMMM y");

        jComboBoxHH.setMaximumRowCount(6);
        jComboBoxHH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha");
        jLabelFecha.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabelFecha.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabelFecha.setPreferredSize(new java.awt.Dimension(50, 16));

        jComboBoxMM.setMaximumRowCount(6);
        jComboBoxMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Hora");
        jLabelHora.setMaximumSize(new java.awt.Dimension(40, 16));
        jLabelHora.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabelHora.setPreferredSize(new java.awt.Dimension(40, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(146, 146, 146)
                                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(114, 114, 114))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelIdPostulante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIdPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int dniPost = 0;
        try {
            dniPost = Integer.parseInt(jTextFieldDNI.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"ERROR: Número de DNI no válido");
            return;
        }
        Postulante post = new PostulanteDaoJDBC().select(dniPost);
        if(post != null) {
            if(CtrlPostulante.esPostulanteActivo(post)) {
                // Obtiene todas las postulaciones y descarta las que no tienen prueba pendiente o que estén canceladas
                ArrayList<Postulacion> listaPostulacion = (ArrayList<Postulacion>) new PostulacionDaoJDBC().select(post.getCodPostulante());
                listaPostulacionPrueba = new ArrayList<>();
                listaPuestosPr = new ArrayList();
                for(int i = 0; i < listaPostulacion.size(); i++) {
                    Postulacion postul = listaPostulacion.get(i);
                    Puesto pst = new PuestoDaoJDBC().select(postul.getCodPuesto());
                    if(postul.getEtapaActual().equals("Prueba") && !pst.getEstadoConvocatoria().equals("cancelada")) {
                        listaPostulacionPrueba.add(postul);
                        listaPuestosPr.add(String.format("%05d",pst.getCodPuesto()) + " - " + pst.getNombre());
                    }
                }
                if(!listaPostulacionPrueba.isEmpty()) {
                    jLabelIdPostulante.setText("Postulante: " + post.getApellido() + ", " + post.getNombre() + " [Código: " + String.format("%05d",post.getCodPostulante()) + "]");
                    jComboBox1.setModel(new DefaultComboBoxModel(listaPuestosPr.toArray()));
                    // Activa otros componentes gráficos
                    activarFormSeleccionarPuesto(true);
                    activarFormBuscarPostulante(false);
                    jLabelIdPostulante.setEnabled(true);
                }
                else {
                    JOptionPane.showMessageDialog(this, "ERROR: El postulante no tiene pruebas pendientes", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                JOptionPane.showMessageDialog(this,CtrlPostulante.mensajeError);
            }
        }
        else {
            JOptionPane.showMessageDialog(this,"ERROR: Postulante inexistente");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < listaPostulacionPrueba.size(); i++) {
            pstl = listaPostulacionPrueba.get(i);
            if(pstl.getCodPuesto() == Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()).substring(0,5))) {
                activarFormSeleccionarPuesto(false);
                activarFormRegistrarPrueba(true);
                String descripcion = new FormatoPruebaDaoJDBC().select(pstl.getCodPuesto(),pstl.getNumPruebaActual()).getDescripcion();
                jTextAreaDescripcion.setText(descripcion);
                return;
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        Prueba p = new Prueba();
        p.setResultado(obtenerResultadoPrueba());
        p.setObservaciones(jTextAreaObservaciones.getText());
        p.setCodPostulante(pstl.getCodPostulante());
        p.setCodPuesto(pstl.getCodPuesto());
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            p.setFecha(Date.valueOf(sdf.format(jDateChooserFecha.getDate())));
        } catch(NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: Debe especificar una fecha", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        p.setHora(Time.valueOf(jComboBoxHH.getSelectedItem() + ":" + jComboBoxMM.getSelectedItem() + ":00"));

        if(CtrlEtapa.esPruebaValida(p)) {
            new PruebaDaoJDBC().insert(p);
            
            int nuevoNumPruebaActual = pstl.getNumPruebaActual() + 1;
            if(nuevoNumPruebaActual > new FormatoPruebaDaoJDBC().getNumeroPruebas(pstl.getCodPuesto())) {
                pstl.setEtapaActual("Examen preocupacional");
            }
            else {
                pstl.setNumPruebaActual(nuevoNumPruebaActual);
            }
            new PostulacionDaoJDBC().update(pstl);
            JOptionPane.showMessageDialog(this, "Se ha registrado la prueba");
            limpiarFormulario();
            activarFormRegistrarPrueba(false);
            jLabelIdPostulante.setText("Postulante:");
            jLabelIdPostulante.setEnabled(false);
            activarFormBuscarPostulante(true);
        }
        else {
            JOptionPane.showMessageDialog(this, CtrlEtapa.mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiarFormulario();
        activarFormRegistrarPrueba(false);
        jLabelIdPostulante.setText("Postulante:");
        jLabelIdPostulante.setEnabled(false);
        activarFormBuscarPostulante(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public int obtenerResultadoPrueba() {
        if(jRadioButton1.isSelected()) return 1;
        else if(jRadioButton2.isSelected()) return 2;
        else if(jRadioButton3.isSelected()) return 3;
        else if(jRadioButton4.isSelected()) return 4;
        else return 5;
    }
    
    public final void activarFormBuscarPostulante(boolean band) {
        jLabelDni.setEnabled(band);
        jTextFieldDNI.setEnabled(band);
        jButtonBuscar.setEnabled(band);
    }
    
    public final void activarFormSeleccionarPuesto(boolean band) {
        jLabelPuesto.setEnabled(band);
        jComboBox1.setEnabled(band);
    }
    
    public final void activarFormRegistrarPrueba(boolean band) {
        jLabelDescripcion.setEnabled(band);
        jTextAreaDescripcion.setEnabled(band);
        jLabelFecha.setEnabled(band);
        jDateChooserFecha.setEnabled(band);
        jLabelHora.setEnabled(band);
        jComboBoxHH.setEnabled(band);
        jComboBoxMM.setEnabled(band);
        jLabelResultado.setEnabled(band);
        jRadioButton1.setEnabled(band);
        jRadioButton2.setEnabled(band);
        jRadioButton3.setEnabled(band);
        jRadioButton4.setEnabled(band);
        jRadioButton5.setEnabled(band);
        jLabelObservaciones.setEnabled(band);
        jTextAreaObservaciones.setEnabled(band);
        jButtonGuardar.setEnabled(band);
        jButtonCancelar.setEnabled(band);
    }
    
    public void limpiarFormulario() {
        jTextFieldDNI.setText("");
        jTextAreaDescripcion.setText("");
        jDateChooserFecha.setDate(null);
        jComboBoxHH.setSelectedIndex(0);
        jComboBoxMM.setSelectedIndex(0);
        jRadioButton1.setSelected(true);
        jTextAreaObservaciones.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxHH;
    private javax.swing.JComboBox<String> jComboBoxMM;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFormatoHora;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelIdPostulante;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelPuesto;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaObservaciones;
    private javax.swing.JTextField jTextFieldDNI;
    // End of variables declaration//GEN-END:variables
}
