/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Etapa;

import Modelo.FormatoEntrevista;
import Modelo.FormatoEntrevistaDaoJDBC;
import Modelo.Postulacion;

/**
 *
 * @author MC1
 */
public class PanelEntrevista extends javax.swing.JPanel {
    private Postulacion postul;
    private PanelCompetencia panelComp[];
    private String competencias[] = {"Presentación",
                                     "Actitud",
                                     "Conversación",
                                     "Disposición",
                                     "Decisión",
                                     "Disponibilidad",
                                     "Transporte",
                                     "Aspecto físico",
                                     "Experiencia",
                                     "Conocimientos",
                                     "Relación",
                                     "Liderazgo",
                                     "Manejo de herramientas"};

    /**
     * Creates new form PanelEntrevista
     */
    public PanelEntrevista() {
        initComponents();
        panelComp = new PanelCompetencia[13];
        jLabel2.setVisible(false);  
    }
    
    public void activarPanel() {
        // Obtiene los campos válidos para esta entrevista
        FormatoEntrevista formatEnt = new FormatoEntrevistaDaoJDBC().select(postul.getCodPuesto());
        boolean competenciaValida[] = new boolean[13];
        competenciaValida[0] = formatEnt.isPresentacion();
        competenciaValida[1] = formatEnt.isActitud();
        competenciaValida[2] = formatEnt.isConversacion();
        competenciaValida[3] = formatEnt.isDisposicion();
        competenciaValida[4] = formatEnt.isDecision();
        competenciaValida[5] = formatEnt.isDisponibilidad();
        competenciaValida[6] = formatEnt.isTransporte();
        competenciaValida[7] = formatEnt.isAspectoFisico();
        competenciaValida[8] = formatEnt.isExperiencia();
        competenciaValida[9] = formatEnt.isConocimientos();
        competenciaValida[10] = formatEnt.isRelacion();
        competenciaValida[11] = formatEnt.isLiderazgo();
        competenciaValida[12] = formatEnt.isManejoHerramientas();
        // Creación de los subpaneles de competencias
        jLabel2.setVisible(true);
        int j = 0;
        for(int i = 0; i < 13; i++) {
            if(competenciaValida[i]) {
                PanelCompetencia pComp = new PanelCompetencia(competencias[i],j == 0);
                pComp.setBounds(0,50 + j*60,1280,60);
                this.add(pComp);
                panelComp[i] = pComp;
                j++;
            }
            else {
                panelComp[i] = null;
            }
        }
        PanelControles pCont = new PanelControles(this);
        pCont.setBounds(0,50 + j * 60,1280,550);
        this.add(pCont);
        setPreferredSize(new java.awt.Dimension(1280,50 + 60 * (j+1) + 550));
    }
    
    public void setPostulacion(Postulacion postul) {
        this.postul = postul;
    }
    
    public Postulacion getPostulacion() {
        return postul;
    }
    
    public PanelCompetencia[] obtenerPanelesCompetencias() {
        return panelComp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 413));
        setMinimumSize(new java.awt.Dimension(1280, 413));
        setPreferredSize(new java.awt.Dimension(1280, 413));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Evaluación de competencias");
        jLabel2.setMaximumSize(new java.awt.Dimension(350, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(350, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(350, 17));
        add(jLabel2);
        jLabel2.setBounds(464, 6, 350, 17);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
