/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Etapa;

import Controlador.CtrlEtapa;
import Modelo.Entrevista;
import Modelo.EntrevistaDaoJDBC;
import Modelo.Postulacion;
import Modelo.PostulacionDaoJDBC;
import java.sql.Date;
import java.sql.Time;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author MC1
 */
public class PanelControles extends javax.swing.JPanel {
    private final PanelEntrevista pe;

    /**
     * Creates new form PanelControles
     * @param pe
     */
    public PanelControles(PanelEntrevista pe) {
        initComponents();
        this.pe = pe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaViveCon = new javax.swing.JTextArea();
        jLabelViveCon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEstudios = new javax.swing.JTextArea();
        jLabelEstudios = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRecomendadoPor = new javax.swing.JTextArea();
        jLabelRecomendadoPor = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxMM = new javax.swing.JComboBox<>();
        jLabelHora = new javax.swing.JLabel();
        jLabelFormatoHora = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jComboBoxHH = new javax.swing.JComboBox<>();
        jLabelFecha = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jTextAreaViveCon.setColumns(20);
        jTextAreaViveCon.setLineWrap(true);
        jTextAreaViveCon.setRows(5);
        jTextAreaViveCon.setWrapStyleWord(true);
        jTextAreaViveCon.setMaximumSize(new java.awt.Dimension(230, 80));
        jTextAreaViveCon.setMinimumSize(new java.awt.Dimension(230, 80));
        jTextAreaViveCon.setPreferredSize(new java.awt.Dimension(230, 80));
        jScrollPane1.setViewportView(jTextAreaViveCon);

        jLabelViveCon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelViveCon.setText("Vive con");
        jLabelViveCon.setMaximumSize(new java.awt.Dimension(250, 16));
        jLabelViveCon.setMinimumSize(new java.awt.Dimension(250, 16));
        jLabelViveCon.setPreferredSize(new java.awt.Dimension(250, 16));

        jTextAreaEstudios.setColumns(20);
        jTextAreaEstudios.setLineWrap(true);
        jTextAreaEstudios.setRows(5);
        jTextAreaEstudios.setWrapStyleWord(true);
        jTextAreaEstudios.setMaximumSize(new java.awt.Dimension(230, 80));
        jTextAreaEstudios.setMinimumSize(new java.awt.Dimension(230, 80));
        jTextAreaEstudios.setPreferredSize(new java.awt.Dimension(230, 80));
        jScrollPane2.setViewportView(jTextAreaEstudios);

        jLabelEstudios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEstudios.setText("Estudios");
        jLabelEstudios.setMaximumSize(new java.awt.Dimension(250, 16));
        jLabelEstudios.setMinimumSize(new java.awt.Dimension(250, 16));
        jLabelEstudios.setPreferredSize(new java.awt.Dimension(250, 16));

        jTextAreaRecomendadoPor.setColumns(20);
        jTextAreaRecomendadoPor.setLineWrap(true);
        jTextAreaRecomendadoPor.setRows(5);
        jTextAreaRecomendadoPor.setWrapStyleWord(true);
        jTextAreaRecomendadoPor.setMaximumSize(new java.awt.Dimension(230, 80));
        jTextAreaRecomendadoPor.setMinimumSize(new java.awt.Dimension(230, 80));
        jTextAreaRecomendadoPor.setPreferredSize(new java.awt.Dimension(230, 80));
        jScrollPane3.setViewportView(jTextAreaRecomendadoPor);

        jLabelRecomendadoPor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRecomendadoPor.setText("Recomendado por");
        jLabelRecomendadoPor.setMaximumSize(new java.awt.Dimension(250, 16));
        jLabelRecomendadoPor.setMinimumSize(new java.awt.Dimension(250, 16));
        jLabelRecomendadoPor.setPreferredSize(new java.awt.Dimension(250, 16));

        jButtonGuardar.setText("Guardar Datos");
        jButtonGuardar.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxMM.setMaximumRowCount(6);
        jComboBoxMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Hora");
        jLabelHora.setMaximumSize(new java.awt.Dimension(40, 16));
        jLabelHora.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabelHora.setPreferredSize(new java.awt.Dimension(40, 16));

        jLabelFormatoHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFormatoHora.setText(":");
        jLabelFormatoHora.setEnabled(false);
        jLabelFormatoHora.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelFormatoHora.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabelFormatoHora.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabelFormatoHora.setPreferredSize(new java.awt.Dimension(60, 16));

        jDateChooserFecha.setDateFormatString("d MMMM y");

        jComboBoxHH.setMaximumRowCount(6);
        jComboBoxHH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha");
        jLabelFecha.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabelFecha.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabelFecha.setPreferredSize(new java.awt.Dimension(50, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(493, 493, 493))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRecomendadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelViveCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelViveCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecomendadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // Verifica que los campos de texto estén llenos y la fecha y hora sean válidas
        Entrevista e = new Entrevista();
        Postulacion postula = pe.getPostulacion();
        PanelCompetencia pCom[] = pe.obtenerPanelesCompetencias();
        e.setPresentacion(pCom[0] != null ? pCom[0].obtenerValor() : 0);
        e.setActitud(pCom[1] != null ? pCom[1].obtenerValor() : 0);
        e.setConversacion(pCom[2] != null ? pCom[2].obtenerValor() : 0);
        e.setDisposicion(pCom[3] != null ? pCom[3].obtenerValor() : 0);
        e.setDecision(pCom[4] != null ? pCom[4].obtenerValor() : 0);
        e.setDisponibilidad(pCom[5] != null ? pCom[5].obtenerValor() : 0);
        e.setTransporte(pCom[6] != null ? pCom[6].obtenerValor() : 0);
        e.setAspectoFisico(pCom[7] != null ? pCom[7].obtenerValor() : 0);
        e.setExperiencia(pCom[8] != null ? pCom[8].obtenerValor() : 0);
        e.setConocimientos(pCom[9] != null ? pCom[9].obtenerValor() : 0);
        e.setRelacion(pCom[10] != null ? pCom[10].obtenerValor() : 0);
        e.setLiderazgo(pCom[11] != null ? pCom[11].obtenerValor() : 0);
        e.setManejoHerramientas(pCom[12] != null ? pCom[12].obtenerValor() : 0);
        e.setViveCon(jTextAreaViveCon.getText());
        e.setEstudios(jTextAreaEstudios.getText());
        e.setRecomendadoPor(jTextAreaRecomendadoPor.getText());
        e.setCodPostulante(postula.getCodPostulante());
        e.setCodPuesto(postula.getCodPuesto());
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            e.setFecha(Date.valueOf(sdf.format(jDateChooserFecha.getDate())));
        } catch(NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: Debe especificar una fecha", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        e.setHora(Time.valueOf(jComboBoxHH.getSelectedItem() + ":" + jComboBoxMM.getSelectedItem() + ":00"));
        // Si la entrevista es válida actualiza BD, sino informa error
        if(CtrlEtapa.esEntrevistaValida(e)) {
            new EntrevistaDaoJDBC().insert(e);
            postula.setEtapaActual("Prueba");
            postula.setNumPruebaActual(1);
            new PostulacionDaoJDBC().update(postula);
            JOptionPane.showMessageDialog(pe, "Se ha registrado la entrevista");
        }
        else {
            JOptionPane.showMessageDialog(this, CtrlEtapa.mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        /*limpiarFormulario();
        activarFormModificarPostulante(false);
        activarFormBuscarPostulante(true);*/
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxHH;
    private javax.swing.JComboBox<String> jComboBoxMM;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabelEstudios;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFormatoHora;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelRecomendadoPor;
    private javax.swing.JLabel jLabelViveCon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaEstudios;
    private javax.swing.JTextArea jTextAreaRecomendadoPor;
    private javax.swing.JTextArea jTextAreaViveCon;
    // End of variables declaration//GEN-END:variables
}