/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Convocatoria;

/**
 *
 * @author MC1
 */
public class ConfigurarEntrevista extends javax.swing.JPanel {

    /**
     * Creates new form ConfigurarEntrevista
     */
    public ConfigurarEntrevista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRutaPdf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jCheckBox1Prese = new javax.swing.JCheckBox();
        jCheckBox2Actit = new javax.swing.JCheckBox();
        jCheckBox3Conve = new javax.swing.JCheckBox();
        jCheckBox4Dispo = new javax.swing.JCheckBox();
        jCheckBox5Decis = new javax.swing.JCheckBox();
        jCheckBox6Dspnb = new javax.swing.JCheckBox();
        jCheckBox7Trans = new javax.swing.JCheckBox();
        jCheckBox8Aspec = new javax.swing.JCheckBox();
        jCheckBox9Exper = new javax.swing.JCheckBox();
        jCheckBox10Conoc = new javax.swing.JCheckBox();
        jCheckBox11Relac = new javax.swing.JCheckBox();
        jCheckBox12Lider = new javax.swing.JCheckBox();
        jCheckBox13Manej = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldFecha1 = new javax.swing.JTextField();
        jLabelRutaPdf1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jLabelRutaPdf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRutaPdf.setText("Fecha");
        jLabelRutaPdf.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabelRutaPdf.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabelRutaPdf.setPreferredSize(new java.awt.Dimension(50, 16));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configurar Entrevista");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 29));

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setMaximumSize(new java.awt.Dimension(200, 22));
        jButtonSiguiente.setMinimumSize(new java.awt.Dimension(200, 22));
        jButtonSiguiente.setPreferredSize(new java.awt.Dimension(200, 22));

        jCheckBox1Prese.setText("Presentación");
        jCheckBox1Prese.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox1Prese.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox1Prese.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox2Actit.setText("Actitud");
        jCheckBox2Actit.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox2Actit.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox2Actit.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox3Conve.setText("Conversación");
        jCheckBox3Conve.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox3Conve.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox3Conve.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox4Dispo.setText("Disposición");
        jCheckBox4Dispo.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox4Dispo.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox4Dispo.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox5Decis.setText("Decisión");
        jCheckBox5Decis.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox5Decis.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox5Decis.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox6Dspnb.setText("Disponibilidad");
        jCheckBox6Dspnb.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox6Dspnb.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox6Dspnb.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox7Trans.setText("Transporte");
        jCheckBox7Trans.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox7Trans.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox7Trans.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox8Aspec.setText("Aspecto físico");
        jCheckBox8Aspec.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox8Aspec.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox8Aspec.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox9Exper.setText("Experiencia");
        jCheckBox9Exper.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox9Exper.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox9Exper.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox10Conoc.setText("Conocimientos");
        jCheckBox10Conoc.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox10Conoc.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox10Conoc.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox11Relac.setText("Relación");
        jCheckBox11Relac.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox11Relac.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox11Relac.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox12Lider.setText("Liderazgo");
        jCheckBox12Lider.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox12Lider.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox12Lider.setPreferredSize(new java.awt.Dimension(200, 20));

        jCheckBox13Manej.setText("Manejo de herramientas");
        jCheckBox13Manej.setMaximumSize(new java.awt.Dimension(200, 20));
        jCheckBox13Manej.setMinimumSize(new java.awt.Dimension(200, 20));
        jCheckBox13Manej.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Competencias");
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(250, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 17));

        jTextFieldFecha.setMaximumSize(new java.awt.Dimension(100, 22));
        jTextFieldFecha.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextFieldFecha.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextFieldFecha1.setMaximumSize(new java.awt.Dimension(100, 22));
        jTextFieldFecha1.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextFieldFecha1.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabelRutaPdf1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRutaPdf1.setText("Hora");
        jLabelRutaPdf1.setMaximumSize(new java.awt.Dimension(40, 16));
        jLabelRutaPdf1.setMinimumSize(new java.awt.Dimension(40, 16));
        jLabelRutaPdf1.setPreferredSize(new java.awt.Dimension(40, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(528, 528, 528))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2Actit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1Prese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8Aspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox9Exper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox7Trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3Conve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox4Dispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox5Decis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox6Dspnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox11Relac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox10Conoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox12Lider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox13Manej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(385, 385, 385))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabelRutaPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRutaPdf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1Prese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2Actit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox8Aspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9Exper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox3Conve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox4Dispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox5Decis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox6Dspnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox7Trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox10Conoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox11Relac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox12Lider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox13Manej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRutaPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRutaPdf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JCheckBox jCheckBox10Conoc;
    private javax.swing.JCheckBox jCheckBox11Relac;
    private javax.swing.JCheckBox jCheckBox12Lider;
    private javax.swing.JCheckBox jCheckBox13Manej;
    private javax.swing.JCheckBox jCheckBox1Prese;
    private javax.swing.JCheckBox jCheckBox2Actit;
    private javax.swing.JCheckBox jCheckBox3Conve;
    private javax.swing.JCheckBox jCheckBox4Dispo;
    private javax.swing.JCheckBox jCheckBox5Decis;
    private javax.swing.JCheckBox jCheckBox6Dspnb;
    private javax.swing.JCheckBox jCheckBox7Trans;
    private javax.swing.JCheckBox jCheckBox8Aspec;
    private javax.swing.JCheckBox jCheckBox9Exper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelRutaPdf;
    private javax.swing.JLabel jLabelRutaPdf1;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldFecha1;
    // End of variables declaration//GEN-END:variables
}
