/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Convocatoria;

import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author EGcri
 */
public class Crear extends javax.swing.JPanel {
    CardLayout cl;
    ArrayList<Object> obj;

    /**
     * Creates new form Crear
     */
    public Crear() {
        initComponents();
        obj = new ArrayList<>();
        NuevoPuesto np = new NuevoPuesto(this,obj);
        this.add(np);
        cl = (CardLayout)this.getLayout();
        cl.addLayoutComponent(np, "NUEVO_PUESTO");
        cl.first(this);
    }
    
    public void agregarPantallas(int numPruebas) {
        ConfigurarEntrevista ce = new ConfigurarEntrevista(this,obj);
        this.add(ce);
        cl.addLayoutComponent(ce,"ENTREVISTA");
        for(int i = 1; i <= numPruebas; i++) {
            String etiqBoton = (i != numPruebas) ? "Siguiente" : "Finalizar";
            ConfigurarPrueba cp = new ConfigurarPrueba(this,i,etiqBoton,obj);
            this.add(cp);
            cl.addLayoutComponent(cp,"PRUEBA_" + i);
        }
    }
    
    public void avanzarPantalla() {
        cl.next(this);
    }
    
    public void resetearPantallas() {
        this.removeAll();
        initComponents();
        obj = new ArrayList<>();
        NuevoPuesto np = new NuevoPuesto(this,obj);
        this.add(np);
        cl = (CardLayout)this.getLayout();
        cl.addLayoutComponent(np, "NUEVO_PUESTO");
        cl.first(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));
        setPreferredSize(new java.awt.Dimension(1280, 550));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}