/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Convocatoria;

import Controlador.CtrlCrearConvocatoria;
import Modelo.Puesto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MC1
 */
public class NuevoPuesto extends javax.swing.JPanel {
    private Crear pantCrear;
    private ArrayList<Object> objeto;

    /**
     * Creates new form NuevoPuesto
     * @param c
     * @param obj
     */
    public NuevoPuesto(Crear c, ArrayList<Object> obj) {
        initComponents();
        pantCrear = c;
        objeto = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelFechaCierre = new javax.swing.JLabel();
        jLabelPruebas = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jSpinnerPruebas = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescrip = new javax.swing.JTextArea();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFechaCierre = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelFechaInicio1 = new javax.swing.JLabel();
        jLabelFormatoFecha = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese los datos del puesto");
        jLabel2.setMaximumSize(new java.awt.Dimension(250, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(250, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 17));

        jLabelFechaInicio.setText("Fecha de inicio");
        jLabelFechaInicio.setMaximumSize(new java.awt.Dimension(110, 16));
        jLabelFechaInicio.setMinimumSize(new java.awt.Dimension(110, 16));
        jLabelFechaInicio.setPreferredSize(new java.awt.Dimension(110, 16));

        jLabelFechaCierre.setText("Fecha de cierre");
        jLabelFechaCierre.setMaximumSize(new java.awt.Dimension(110, 16));
        jLabelFechaCierre.setMinimumSize(new java.awt.Dimension(110, 16));
        jLabelFechaCierre.setPreferredSize(new java.awt.Dimension(110, 16));

        jLabelPruebas.setText("Número de pruebas");
        jLabelPruebas.setMaximumSize(new java.awt.Dimension(140, 16));
        jLabelPruebas.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabelPruebas.setPreferredSize(new java.awt.Dimension(140, 16));

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonSiguiente.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonSiguiente.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jSpinnerPruebas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinnerPruebas.setMaximumSize(new java.awt.Dimension(64, 22));

        jTextAreaDescrip.setColumns(20);
        jTextAreaDescrip.setLineWrap(true);
        jTextAreaDescrip.setRows(5);
        jTextAreaDescrip.setWrapStyleWord(true);
        jTextAreaDescrip.setMaximumSize(new java.awt.Dimension(332, 60));
        jTextAreaDescrip.setMinimumSize(new java.awt.Dimension(332, 60));
        jTextAreaDescrip.setPreferredSize(new java.awt.Dimension(332, 60));
        jScrollPane1.setViewportView(jTextAreaDescrip);

        jTextFieldFechaInicio.setMaximumSize(new java.awt.Dimension(100, 22));
        jTextFieldFechaInicio.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextFieldFechaInicio.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Descripción");
        jLabel3.setMaximumSize(new java.awt.Dimension(230, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(230, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(230, 16));

        jTextFieldFechaCierre.setMaximumSize(new java.awt.Dimension(100, 22));
        jTextFieldFechaCierre.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextFieldFechaCierre.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextFieldNombre.setMaximumSize(new java.awt.Dimension(332, 22));
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(332, 22));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(332, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Puesto");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 29));

        jLabelFechaInicio1.setText("Nombre");
        jLabelFechaInicio1.setMaximumSize(new java.awt.Dimension(140, 16));
        jLabelFechaInicio1.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabelFechaInicio1.setPreferredSize(new java.awt.Dimension(140, 16));

        jLabelFormatoFecha.setText("dd/mm/aaaa");
        jLabelFormatoFecha.setEnabled(false);
        jLabelFormatoFecha.setMaximumSize(new java.awt.Dimension(140, 16));
        jLabelFormatoFecha.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabelFormatoFecha.setPreferredSize(new java.awt.Dimension(140, 16));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 22));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(452, 452, 452))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(497, 497, 497))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelFormatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(474, 474, 474))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFormatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        Puesto puesto = new Puesto();
        puesto.setNombre(jTextFieldNombre.getText());
        puesto.setDescripcion(jTextAreaDescrip.getText());
        String fi = jTextFieldFechaInicio.getText();
        String fc = jTextFieldFechaCierre.getText();
        puesto.setEstadoConvocatoria("abierta");
        if(CtrlCrearConvocatoria.esValido(puesto, fi, fc)) {
            // almacena objeto válido en array list
            objeto.add(puesto);
            int valor = (int)jSpinnerPruebas.getValue();
            pantCrear.agregarPantallas(valor);
            pantCrear.avanzarPantalla();
        }
        else {
            JOptionPane.showMessageDialog(this, CtrlCrearConvocatoria.mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiarFormulario();
        pantCrear.resetearPantallas();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void limpiarFormulario() {
        jTextFieldNombre.setText("");
        jTextAreaDescrip.setText("");
        jTextFieldFechaInicio.setText("");
        jTextFieldFechaCierre.setText("");
        jSpinnerPruebas.setValue(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFechaCierre;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelFechaInicio1;
    private javax.swing.JLabel jLabelFormatoFecha;
    private javax.swing.JLabel jLabelPruebas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPruebas;
    private javax.swing.JTextArea jTextAreaDescrip;
    private javax.swing.JTextField jTextFieldFechaCierre;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
