/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.GestionUsuarios;
import Modelo.UsuarioDao;
import Modelo.UsuarioDaoJDBC;
import Modelo.Usuario;
import Controlador.CtrlContraseñaaHash;
import Controlador.CtrlUsuarios;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author EGcri
 */
public class CrearUsuario extends javax.swing.JPanel {

    /**
     * Creates new form crearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        GuardarjButton = new javax.swing.JButton();
        NombreUsuariojTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        PermisoAdministradorjRadioButton = new javax.swing.JRadioButton();
        PermisoOperadorjRadioButton = new javax.swing.JRadioButton();
        PermisoPostulantejRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jLabel1.setText("Nombre de usuario");

        GuardarjButton.setText("Guardar");
        GuardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña");

        jLabel3.setText("Repetir Contraseña");

        buttonGroup1.add(PermisoAdministradorjRadioButton);
        PermisoAdministradorjRadioButton.setText("Administrador");

        buttonGroup1.add(PermisoOperadorjRadioButton);
        PermisoOperadorjRadioButton.setText("Operador");

        buttonGroup1.add(PermisoPostulantejRadioButton);
        PermisoPostulantejRadioButton.setText("Postulante");

        jLabel4.setText("Permisos");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Crear Usuario");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Datos de la nueva cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)
                            .addComponent(PermisoAdministradorjRadioButton))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NombreUsuariojTextField)
                                .addComponent(jPasswordField1)
                                .addComponent(jPasswordField2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(PermisoPostulantejRadioButton)))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PermisoOperadorjRadioButton)
                            .addComponent(GuardarjButton))))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PermisoAdministradorjRadioButton)
                    .addComponent(PermisoOperadorjRadioButton)
                    .addComponent(PermisoPostulantejRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(GuardarjButton)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarjButtonActionPerformed
       Usuario usuario = new Usuario();        
       char[] password1 = jPasswordField1.getPassword();
       char[] password2 = jPasswordField2.getPassword();
       
       usuario.setNombreUsuario(NombreUsuariojTextField.getText());
       if(NombreUsuariojTextField.getText().length() == 0)
           mostrarVentanaDeError(CtrlUsuarios.errorUsuarioVacio);
       if(Arrays.equals(password1, password2))
        usuario.setContraseñaUsuario(CtrlContraseñaaHash.hasher(new String (password1)));
       else
           mostrarVentanaDeError(CtrlUsuarios.errorContraseñaVacia);
       if(PermisoAdministradorjRadioButton.isEnabled())
           usuario.setPermisosUsuario(1);
       else if(PermisoOperadorjRadioButton.isEnabled())
           usuario.setPermisosUsuario(2);
       else if(PermisoPostulantejRadioButton.isEnabled())
           usuario.setPermisosUsuario(3);
       else
           mostrarVentanaDeError(CtrlUsuarios.errorSinSeleccion);
       
       UsuarioDao UsuarioDao = new UsuarioDaoJDBC();
       if(CtrlUsuarios.chequeoFinal(usuario))
       {
            UsuarioDao.insert(usuario);
            JOptionPane.showMessageDialog(this,"Usuario Creado");
       }
       else{
           JOptionPane.showMessageDialog(this, CtrlUsuarios.errorContraseñaVacia, "Error", JOptionPane.ERROR_MESSAGE);
       }
       
        
    }//GEN-LAST:event_GuardarjButtonActionPerformed
    public void limpiarFormulario(){
        NombreUsuariojTextField.setText("");
        PermisoAdministradorjRadioButton.setSelected(false);
        PermisoOperadorjRadioButton.setSelected(false);
        PermisoPostulantejRadioButton.setSelected(false);
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }
    public static void mostrarVentanaDeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarjButton;
    private javax.swing.JTextField NombreUsuariojTextField;
    private javax.swing.JRadioButton PermisoAdministradorjRadioButton;
    private javax.swing.JRadioButton PermisoOperadorjRadioButton;
    private javax.swing.JRadioButton PermisoPostulantejRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
