/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.GestionUsuarios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Controlador.CtrlUsuarios;
import Modelo.Usuario;
import Modelo.UsuarioDao;
import Modelo.UsuarioDaoJDBC;

/**
 *
 * @author EGcri
 */
public class EliminarUsuario extends javax.swing.JPanel {
    
    private Usuario usuario = null;
    UsuarioDao inter = new UsuarioDaoJDBC();
    /**
     * Creates new form eliminarUsuario
     */
    public EliminarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreUsuariojTextField = new javax.swing.JTextField();
        BuscarjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LabelPermiso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelUID = new javax.swing.JLabel();
        EliminarUsuariojButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 550));
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jLabel1.setText("Nombre de Usuario");

        NombreUsuariojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreUsuariojTextFieldKeyPressed(evt);
            }
        });

        BuscarjButton.setText("Buscar");
        BuscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Permisos ");

        LabelPermiso.setText("LabelPermiso");

        jLabel4.setText("UID");

        LabelUID.setText("LabelUID");

        EliminarUsuariojButton.setText("Eliminar");
        EliminarUsuariojButton.setEnabled(false);
        EliminarUsuariojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuariojButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Eliminar Usuario");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Buscar Usuario");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Datos del Usuario");

        jLabel9.setText("Esta accion es permanente y no se pueden recuperar los datos de la misma una vez completada ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EliminarUsuariojButton)
                .addGap(580, 580, 580))
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUID)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NombreUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BuscarjButton))
                            .addComponent(LabelPermiso)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel9))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelPermiso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelUID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(93, 93, 93)
                .addComponent(EliminarUsuariojButton)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuariojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreUsuariojTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            BuscarjButtonActionPerformed(null);
    }//GEN-LAST:event_NombreUsuariojTextFieldKeyPressed

    private void BuscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarjButtonActionPerformed
        String nombreUsuario = NombreUsuariojTextField.getText();
        if(nombreUsuario.length() == 0 || " ".equals(nombreUsuario) ) JOptionPane.showMessageDialog(this, CtrlUsuarios.errorUsuarioVacio, TOOL_TIP_TEXT_KEY, HEIGHT);
        else
        {           
            this.usuario = inter.search(nombreUsuario);
            String permisos = "";
            if(usuario != null)
            { 
                switch (this.usuario.getPermisosUsuario()) {
                    case 0:
                        permisos = "Administrador";
                        break;
                    case 1:
                        permisos = "Operador";
                        break;
                    case 2:
                        permisos = "Postulante";
                        break;
                    default:
                        break;
                }
                LabelPermiso.setText(permisos);
                LabelUID.setText(String.valueOf(this.usuario.getUidUsuario()));
                EliminarUsuariojButton.setEnabled(true);                
            }
            
            
        }
    }//GEN-LAST:event_BuscarjButtonActionPerformed

    private void EliminarUsuariojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuariojButtonActionPerformed

      if(inter.delete(this.usuario) == 1)
      {
          JOptionPane.showMessageDialog(this, "Eliminación correcta");
      }
      
    }//GEN-LAST:event_EliminarUsuariojButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarjButton;
    private javax.swing.JButton EliminarUsuariojButton;
    private javax.swing.JLabel LabelPermiso;
    private javax.swing.JLabel LabelUID;
    private javax.swing.JTextField NombreUsuariojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
